### ISSUE TITLE
There should be an easy way to download the version of events calendar that event codes plugin supports.

### ISSUE THREAD

**Issue by Valenie** [ajency/events-wordpress-plugin#1]
Tested on: ver 0.0.2

The message should be - To begin using Event Codes, please install The Events Calendar. We support versions from 4.4.3 upto version 4.4.4.  **Click** here to download the latest version of The Events Calendar we support.

**Comment by antoniojfurtado** [comment]
I've made available the latest version that we support via a download link in the plugin missing/version message
