### ISSUE TITLE
Mozilla | When the name of the event is big the alignment of the event name is not proper

### ISSUE THREAD

**Issue by Valenie** [ajency/events-wordpress-plugin#19]
Theme : https://demo.themegrill.com/demos/?theme=Spacious

![image](https://cloud.githubusercontent.com/assets/19943710/25611496/f2008878-2f44-11e7-938f-107003629186.png)

**Comment by renukaajency** [comment]
Happens when its a long word - fixed it, it will break in the middle of the word. Word will break just about anywhere now, can't be controlled...

![image](https://cloud.githubusercontent.com/assets/11813307/25615338/39b85344-2f54-11e7-886f-4e51074a7cd3.png)
