### ISSUE TITLE
When a new plugin is installed above another plugin, then an error is generated

### ISSUE THREAD

**Issue by Valenie** [ajency/events-wordpress-plugin#24]
wp ver - 4.4.7
Events code ver - 0.3.5

![image](https://cloud.githubusercontent.com/assets/19943710/25797953/ff025ec2-33fc-11e7-9f50-c6fc8ad5b8eb.png)

**Comment by antoniojfurtado** [comment]
You need to replace the plugin folder, same plugins can be installed like this
