### ISSUE TITLE
Unable to see the menu item "Event Codes" 

### ISSUE THREAD

**Issue by Valenie** [ajency/events-wordpress-plugin#25]
Event codes Ver - 0.3.5
Events calendar ver - 4.4.5
wp ver - 4.7.4

![image](https://cloud.githubusercontent.com/assets/19943710/25798664/b26c095c-33ff-11e7-84a7-e06a0926358e.png)

**Comment by antoniojfurtado** [comment]
I could not reproduce this, can u give me login details for cloudpath,ajency.in?

**Comment by antoniojfurtado** [comment]
Ohh!! wait, This was fixed and in release 0.3.7, along with load more issue
