### ISSUE TITLE
Only when the Featured option has value true, the featured events should be displayed. Similarly for the past option

### ISSUE THREAD

**Issue by Valenie** [ajency/events-wordpress-plugin#27]
Wp ver - 4.7.4
Events code ver - 0.3.5
Events Calendar - 4.4.5

The Featured events are displayed for any value of featured option.

![image](https://cloud.githubusercontent.com/assets/19943710/25803790/39759286-3416-11e7-9ca9-3744807ccf06.png)

Also for the past option.
![image](https://cloud.githubusercontent.com/assets/19943710/25804615/2c248dea-341a-11e7-8a20-6bd9a2ff4264.png)

**Comment by antoniojfurtado** [comment]
I think featured events should be displayed in the normal list also,.
If we need to hide featured from normal lists, we should have a specific option to not include featured events.

As a user I would want to see my featured events among-st my upcoming/past events and we could use an indicator to indicate that an event is featured.

Can debate on this, Does the other shortcode plugin not include featured events in their normal list?
