### ISSUE TITLE
Row - alternate gray value does not work

### ISSUE THREAD

**Issue by Valenie** [ajency/events-wordpress-plugin#33]
Theme: http://www.wpexplorer.com/elegant-free-wordpress-theme/
Wp ver- 4.7.4
Events code ver- 0.4.1
Events calendar - 4.5.0.2

![image](https://cloud.githubusercontent.com/assets/19943710/26142879/237dfdd8-3b00-11e7-824e-125904f41052.png)

**Comment by renukaajency** [comment]
Alternate grey is present but due to the background color of the theme, the alternate rows are not appearing grey. Can't be fixed
