### ISSUE TITLE
Mobile - Portrait | Location value is close to the label

### ISSUE THREAD

**Issue by Valenie** [ajency/events-wordpress-plugin#34]
Theme: http://www.wpexplorer.com/thoughts-wordpress-theme/  --- Normal theme
Wp ver : 4.7.4
Events code: 0.4.1
Events calendar: 4.5.0.2

![image](https://cloud.githubusercontent.com/assets/19943710/26146913/71e9afc6-3b0f-11e7-853b-997c9f38ebf5.png)

**Comment by renukaajency** [comment]
Issue with the theme - the theme css has set a width and padding to the main container which should not be overwritten using plugin css as it may cause the theme to break.
