### ISSUE TITLE
The alignment of amount is not proper

### ISSUE THREAD

**Issue by Valenie** [ajency/events-wordpress-plugin#41]
Theme: https://colorlib.com/wp/themes/activello/ (Bootstrap theme - bootstrap setting off)
https://colorlib.com/wp/themes/dazzling/
Wp ver: 4.74
Events code ver: 0.4.1
Events calendar: 4.5.0.5

![image](https://cloud.githubusercontent.com/assets/19943710/26234110/c507ad22-3c7f-11e7-831f-4e0010d01891.png)

![image](https://cloud.githubusercontent.com/assets/19943710/26234117/cb437cac-3c7f-11e7-8ac7-07fd91f7f54c.png)

**Comment by renukaajency** [comment]
@antoniojfurtado    In **non-bootstrap html** of the shortcode please remove 'pull-right' for the price -
![screen shot 2017-05-22 at 5 33 34 pm](https://cloud.githubusercontent.com/assets/11813307/26307932/aafc5972-3f14-11e7-9e85-06c88da5e972.png)

**Comment by antoniojfurtado** [comment]
@renukaajency done
