### ISSUE TITLE
Safari | The content for tabular view is too close 

### ISSUE THREAD

**Issue by Valenie** [ajency/events-wordpress-plugin#42]
Theme: https://demo.themegrill.com/demos/?theme=Envince  (Normal Theme)
Wp ver: 4.74
Events code ver: 0.4.1
Events calendar: 4.5.0.5

![image](https://cloud.githubusercontent.com/assets/19943710/26238614/785123ce-3c97-11e7-90b3-110c70c711f1.png)

**Comment by renukaajency** [comment]
@antoniojfurtado there's an extra 'row' class added to the divs with class 'aj-table__info' in the **non-bootstrap** version. Please remove those -

![11](https://cloud.githubusercontent.com/assets/11813307/26307425/11903e36-3f12-11e7-9a19-ea973cad7765.jpg)

**Comment by antoniojfurtado** [comment]
@renukaajency done
