### ISSUE TITLE
Based on the value for the style parameter the views should be different.

### ISSUE THREAD

**Issue by Valenie** [ajency/events-wordpress-plugin#45]
Tested on:
Events code ver : 0.4.8
Events cal: 4.5.0.2
wp ver: 4.7.4  

Following views: 
 [event_codes view= ‘list’ style= ‘basic’] 
            [event_codes view= ‘list’ style= ‘big-date’] 
            [event_codes view= ‘list’ style= ‘card-overlay’] 
            [event_codes view= ‘list’ style= ‘complete-overlay’]           

Current Behaviour: Only complete overlay style  is displayed.

**Comment by antoniojfurtado** [comment]
Fixed in 0.4.9
