### ISSUE TITLE
When the event codes plugin is activated, the data on the site is not displayed

### ISSUE THREAD

**Issue by Valenie** [ajency/events-wordpress-plugin#5]

**Comment by antoniojfurtado** [comment]
Currently our plugin will support wordpress versions 4.4.0 and above as some functions we use for load more functionality are not available in lesser versions.
eg https://developer.wordpress.org/reference/functions/rest_url/ and other rest_api functions
Will have to handle this gracefully using older admin-ajax mechanisms for older versions.

http://shortfilm.staging.wpengine.com uses WP 4.1.15 on staging site
