### ISSUE TITLE
List View - basic, the date fields should be of fixed size. 

### ISSUE THREAD

**Issue by Valenie** [ajency/events-wordpress-plugin#50]
The size of the date field varies based on the date and time settings

![image](https://cloud.githubusercontent.com/assets/19943710/26545141/20793c0c-4482-11e7-92fa-87b048167ef5.png)

![image](https://cloud.githubusercontent.com/assets/19943710/26545376/04bbf38c-4483-11e7-9596-c1253ea67f27.png)

**Comment by renukaajency** [comment]
If it had a fixed size, you'll get a lot of blank space in the box, which will look bad
