### ISSUE TITLE
List view - card overlay, view all action should be in line with the card

### ISSUE THREAD

**Issue by Valenie** [ajency/events-wordpress-plugin#52]
Theme: https://colorlib.com/wp/themes/illdy/ (Bootstrap - setting on/off)
https://colorlib.com/wp/themes/shapely/
https://colorlib.com/wp/themes/activello/
https://colorlib.com/wp/themes/dazzling/

Tested on:
Events code ver : 0.4.9
Events cal: 4.5.0.2
wp ver: 4.7.4

![image](https://cloud.githubusercontent.com/assets/19943710/26546247/b020b4c6-4486-11e7-87fa-f4c831f137c7.png)

**Comment by renukaajency** [comment]
Done
