### ISSUE TITLE
List View- There should be a tooltip when the event name is long

### ISSUE THREAD

**Issue by Valenie** [ajency/events-wordpress-plugin#54]
Tested on:
Events code ver : 0.4.9
Events cal: 4.5.0.2
wp ver: 4.7.4

![image](https://cloud.githubusercontent.com/assets/19943710/26546829/962a849a-4489-11e7-86a7-088bccd94764.png)

**Comment by renukaajency** [comment]
@antoniojfurtado for the event name add title attribute with the event name, something like this -

`<a href="..." title="Event name goes here">Event name goes here</a>`
