### ISSUE TITLE
Mobile - Landscape, List view - Card overlay | When image is added, part of the image of 1 event is displayed for the other event

### ISSUE THREAD

**Issue by Valenie** [ajency/events-wordpress-plugin#55]
Theme: https://colorlib.com/wp/themes/illdy/ (Bootstrap - setting on/off)
https://colorlib.com/wp/themes/shapely/
https://colorlib.com/wp/themes/activello/
https://colorlib.com/wp/themes/dazzling/

Tested on:
Events code ver : 0.4.9
Events cal: 4.5.0.2
wp ver: 4.7.4

![image](https://cloud.githubusercontent.com/assets/19943710/26547505/093c839a-448d-11e7-95a1-11d2f810f3d1.png)

**Comment by renukaajency** [comment]
Fixed
