### ISSUE TITLE
List view - complete overlay, the space between the image and data is too much

### ISSUE THREAD

**Issue by Valenie** [ajency/events-wordpress-plugin#57]
Theme: https://wordpress.org/themes/edsbootstrap/ ( Bootstrap setting on/off)

Tested on:
Events code ver : 0.4.9
Events cal: 4.5.0.2
wp ver: 4.7.4

![image](https://cloud.githubusercontent.com/assets/19943710/26548381/8c115292-4491-11e7-8191-87398bf7ce9e.png)

**Comment by renukaajency** [comment]
its percentage based, depending on the screensize the space varies.
