### ISSUE TITLE
When any gibberish is passed as view value and also as the style value, it should give the default view as list and style should be basic.

### ISSUE THREAD

**Issue by Valenie** [ajency/events-wordpress-plugin#58]
Tested on:
Events code ver : 0.4.9
Events cal: 4.5.0.2
wp ver: 4.7.4

Shortcode passed:
[event_codes view='xxx' style= 'card' row='alternate-gray' showtime='true' description='true' count='3']

View: 
![image](https://cloud.githubusercontent.com/assets/19943710/26580597/6487ce5c-4556-11e7-9f8c-b33d772c5a70.png)

**Comment by antoniojfurtado** [comment]
0.4.9.1
