### ISSUE TITLE
Location link should open in a new tab

### ISSUE THREAD

**Issue by Valenie** [ajency/events-wordpress-plugin#60]
Tested on:
Events code ver : 0.4.9
Events cal: 4.5.0.2
wp ver: 4.7.4

![image](https://cloud.githubusercontent.com/assets/19943710/26616437/2d4e2634-45ec-11e7-90bc-6ca66f5192ae.png)

**Comment by renukaajency** [comment]
@antoniojfurtado please add `target="_blank"` for the location anchors
