### ISSUE TITLE
List View- Amount is not displayed properly

### ISSUE THREAD

**Issue by Valenie** [ajency/events-wordpress-plugin#61]
Theme: http://www.wpexplorer.com/elegant-free-wordpress-theme/ (Normal)
http://www.wpexplorer.com/today-free-wordpress/
NOTE: This is on Safari also
Tested on:
Events code ver : 0.4.9
Events cal: 4.5.0.2
wp ver: 4.7.4

![image](https://cloud.githubusercontent.com/assets/19943710/26616455/50fe04d2-45ec-11e7-9d8b-662d51a85cba.png)

**Comment by renukaajency** [comment]
Done
