### ISSUE TITLE
List View - Amount value is too big 

### ISSUE THREAD

**Issue by Valenie** [ajency/events-wordpress-plugin#64]
Theme: https://demo.themegrill.com/demos/?theme=Envince (Normal)
http://www.wpexplorer.com/thoughts-wordpress-theme/

Tested on:
Events code ver : 0.4.9
Events cal: 4.5.0.2
wp ver: 4.7.4

![image](https://cloud.githubusercontent.com/assets/19943710/26616609/8c80408c-45ed-11e7-8c7e-3f3da7bcc30b.png)

**Comment by renukaajency** [comment]
Depends on the theme
