### ISSUE TITLE
List view - Mobile | The event details appear separately from the image (Portrait + landscape)

### ISSUE THREAD

**Issue by Valenie** [ajency/events-wordpress-plugin#66]
Theme: https://demo.themegrill.com/demos/?theme=Spacious (Normal)

Tested on:
Events code ver : 0.4.9
Events cal: 4.5.0.2
wp ver: 4.7.4

![image](https://cloud.githubusercontent.com/assets/19943710/26616786/db8a1dc8-45ee-11e7-93dd-ffd75e832986.png)

**Comment by renukaajency** [comment]
Done
