### ISSUE TITLE
IE | When the date has time, for list view -big date style the time appears on 2 lines

### ISSUE THREAD

**Issue by Valenie** [ajency/events-wordpress-plugin#68]
Theme: https://demo.themegrill.com/demos/?theme=Spacious (Normal)

Tested on:
Events code ver : 0.4.9
Events cal: 4.5.0.2
wp ver: 4.7.4

![image](https://cloud.githubusercontent.com/assets/19943710/26617100/d34b0ff8-45f0-11e7-8fff-7f5a1f5beaa7.png)

**Comment by renukaajency** [comment]
Theme issue - with the font sizes

**Comment by renukaajency** [comment]
Done
