### ISSUE TITLE
List View - Bigdate, if time is set then time displays on 2 lines

### ISSUE THREAD

**Issue by Valenie** [ajency/events-wordpress-plugin#69]
Theme: http://www.wpexplorer.com/thoughts-wordpress-theme/ (Normal)

Tested on:
Events code ver : 0.4.9
Events cal: 4.5.0.2
wp ver: 4.7.4

![image](https://cloud.githubusercontent.com/assets/19943710/26617233/ac90b164-45f1-11e7-91ac-1d33e2b88c58.png)

**Comment by renukaajency** [comment]
issue with the theme
