### ISSUE TITLE
Warning message is displayed on the settings page as well as on the site page

### ISSUE THREAD

**Issue by Valenie** [ajency/events-wordpress-plugin#7]
![image](https://cloud.githubusercontent.com/assets/19943710/25522682/76725888-2c21-11e7-87dd-315c2cb768fa.png)

![image](https://cloud.githubusercontent.com/assets/19943710/25522726/964dacc0-2c21-11e7-91f7-768b69a6be07.png)

**Comment by anujkhurana** [comment]
Do turn on the wp debug mode to true on any site where you test. @Antonio
can show turn on the debug mode for you. But all testing should be with
debug mode on and all warnings should be logged as bugs.
