### ISSUE TITLE
List View - Complete overlay, lot of space between description and image

### ISSUE THREAD

**Issue by Valenie** [ajency/events-wordpress-plugin#70]
http://www.wpexplorer.com/thoughts-wordpress-theme/(Normal)

Tested on:
Events code ver : 0.4.9
Events cal: 4.5.0.2
wp ver: 4.7.4

![image](https://cloud.githubusercontent.com/assets/19943710/26617371/7a8e44dc-45f2-11e7-8f99-24fa54d30377.png)

**Comment by renukaajency** [comment]
same as #57
